apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: docker.pkg.github.com/anarcher/hello-ghact-argocd/hello-world
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
profiles:
- name: test
  build:
    local:
      push: false
- name: publish
  build:
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
    local:
      push: true
