name: skaffold-build
on: 
  push:
    branches:
    - '**'
    tags-ignore:
    - 'v*'
    paths-ignore:
    - 'k8s/**'
    - '.github/workflows/publish.yml'
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: skaffold build
      uses: anarcher/skaffold-action@v1
      with:
        skaffold: build -p test
