name: skaffold-publish
on: 
  push:
    tags:
    - v*
jobs:
  publish:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: skaffold build & publish - ${{ github.ref }}
      uses: anarcher/skaffold-action@master
      with:
        skaffold: build -p publish
        kustomize: edit set image anarcher/hello-ghact-argocd:${IMAGE_TAG} 
        kustomize_path: ./k8s/prod/
        docker_username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
      env:
        IMAGE_TAG: ${{ github.ref }}
    - run: cat ./k8s/prod/kustomization.yaml
    - name: commit and push k8s manifests
      run: |
        git config --global user.email "github-action@github"
        git config --global user.name "github-action"
        git commit ./k8s/prod/ -m "Update to ${IMAGE_TAG}"
        git push 
