name: skaffold-publish
on: 
  push:
    tags:
    - v*
jobs:
  publish:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: skaffold build
      uses: anarcher/skaffold-action@master
      with:
        skaffold: build -p publish
        docker_username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
      env:
        IMAGE_TAG: ${{ github.ref }}
