name: skaffold-publish
on: 
  push:
    tags:
    - v*
jobs:
  publish:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: skaffold build & publish - ${{ github.ref }}
      uses: anarcher/skaffold-action@master
      with:
        skaffold: build -p publish
        kustomize: edit set image anarcher/hello-ghact-argocd:${IMAGE_TAG} 
        kustomize_path: ./k8s/prod/
        docker_username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        docker_password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
      env:
        IMAGE_TAG: ${{ github.ref }}
    - run: cat ./k8s/prod/kustomization.yaml
    - name: commit k8s manifests
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "github-action"
        echo "Update k8s manifests to ${{ github.ref }}" | git commit ./k8s/prod/ --file - 
    - name: push k8s manifests 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
  publish-config:
    needs: publish
    runs-on: ubuntu-latest  
    steps:
    - name: checkout config repository
      uses: actions/checkout@v1
      with:
        repository: anarcher/hello-ghact-argocd-config
        ref: refs/heads/master
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ./hello-ghact-argocd/
    - name: kustomize
      uses: anarcher/skaffold-action@master
      with:
        kustomize: edit set image anarcher/hello-ghact-argocd:${IMAGE_TAG}
        kustomize_path: ./prod/
      env:
        IMAGE_TAG: ${{ github.ref }}
    - name: commit config repository
      run: |
        git config --global user.email "github-action@example.com"
        git config --global user.name "github-action"
        echo "Update k8s manifests to ${{ github.ref }}" | git commit .  --file - 
    - name: push config repository
      uses: anarcher/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        directory: .
        repository: anarcher/hello-ghact-argocd-config
